dbt_bigquery:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: athena-469720
      dataset: "{{ env_var('DBT_DBNAME') }}"
      threads: 4   # Must be a value of 1 or greater
      keyfile: C:/Users/fabio.silvestre/Documents/bigquery/athena-469720-77942e33fe63.json


      